### ISSUE TITLE
Can omnisci work with pure memory mode ?

### ISSUE THREAD

**Issue by titawork** [omnisci/omniscidb#361]
OmniSci is an "in-memory" database. And it  write data of table into disk.
These are some situation such as "load data into OmniSci -> analysis data -> export data". 
In this situation It looks write table into disk is not necessary.
Can OmniSci work with pure memory mode ? 
Or if we will load large of data into Omnisci, 
will the procedure of writing to disk be the weak point ？
In our testing of data analysis, load data and export always consume 5/6  of the time. And the disk is busy when loading data.
Such Load data: 80 s, export data: 60s, caculate : 30s. 
If the performance of load data can be improved, it will be great thing for our work of data analysis. I think work with pure memory mode can help somehow.

**Comment by cdessanti** [comment]
Yes, omnisci is an in-memory **database**, and this means that the data has to be written on a persistent media, like disks for further use;
while loading data directly in-memory looks to be an excellent idea, on real scenarios, it's very unlikely that all the columns are going to be immediately used by the users and for this reason, only the columns referenced by the queries are loaded from disk to in system ram.
If you load all the columns of a table directly in-memory, you are likely going to trash those caches, causing frequent evictions of the data, causing a lot of disk traffic.
It's extraordinary that you are experiencing a lot of disk waits because in my experience the load is more constrained by the availability of CPUs processing power than disk; if you think the disk is the problem you can fine tune kernel parameters of your server to increase the availability of  fs caches, or if you aren't interested on persists at all your data, use a ram disk as mapd_storage for this kind of workload

**Comment by titawork** [comment]
Thank you very much! Your advice of "use a ram disk as mapd_storage for this kind of workload" could be an excellent idea!

**Comment by cdessanti** [comment]
Maybe is worth a try but I don't believe you will get significant speedups, less than you are using very slow disks.
Every time you will remount the ram disk you will have to reinit the database and recreate tables because you will lose all the data. 

I measured a lot of times the impact of disks on loads and with writes being cached by filesystem caching mechanism it never seemed a limiting factor to me.

**Comment by cdessanti** [comment]
I was thinking about your problem; have you tried to hide some latency overlapping the executions using two tables?

at t0 you load table1
at t1 you run the computing part on table1 and at the same time you load table2 on another thread
at t2 you run the computing part on table2 and unload the table 1 (this would be serialized)
at t3 you load the table1 and unload table2
and so on.

It's not perfect, but you should save some time

**Comment by titawork** [comment]
Thank you very much for you reply.
I tried mount $OMNISCI_STROAGE/data/mapd_data to RAM, The load performance can be improved 1/2. Such as I load 20,000,000 records from oracle and 5,000,000 record from file,  before mounting to RAM it takes 85s, But only 42s after. And before mounting to RAM, I only can use 10 threads to load data from oracle, because my disk limit the speed. 
In my situation, tables don't need keep in the database all the time, I first load all data into OmniSci, and delete them after caculate finished. 
I think in my situation, mount mapd_data folder could be a good solution. 
And I also need replace from mechanical hard disk to SSD right now.
