### ISSUE TITLE
Exception occurred: type not serializable:

### ISSUE THREAD

**Issue by ienkovich** [omnisci/omniscidb#371]
Trying to run TPC-H queries on Omnisci I got this error for 6 of 22 queries

ERROR CalciteServerHandler:process:204 - Exception occurred: type not serializable: [$cor0] (type com.google.common.collect.SingletonImmutableSet)

I attach schema definition and a couple of failed queries. Is it a bug or some kind of unsupported yet queries?

[create_tables.txt](https://github.com/omnisci/omniscidb/files/3461802/create_tables.txt)
[Q2.txt](https://github.com/omnisci/omniscidb/files/3461803/Q2.txt)
[Q4.txt](https://github.com/omnisci/omniscidb/files/3461804/Q4.txt)

**Comment by cdessanti** [comment]
@ienkovich 

the problem is we currently don't support correlated subqueries. I can give the queries rewritten to run on omnisci, but generally the performances are not stellar (yet).

as an example Q04 has to be rewritten in this way

select
o_orderpriority,
count(*) as order_count
from
orders
where
o_orderdate >= date '1993-07-01'
and o_orderdate < date '1993-07-01' + interval '3' month
and o_orderkey in (select distinct l_orderkey as subq_l_orderkey from lineitem
where  l_commitdate < l_receiptdate)
group by
o_orderpriority
order by
o_orderpriority;

you have to disable watchdog to run some of those rewritten queries (depending of tpch sizing you are using)

**Comment by ienkovich** [comment]
Thanks for the help!
