### ISSUE TITLE
Immerse / Web does not work - missing frontend directory?

### ISSUE THREAD

**Issue by baretomas** [omnisci/omniscidb#385]
Hello,

I installed omnisci on a dedicated centos 7 server, and now want to connect to the web portal on port 6273. Ive started omnisci_web_server and it is looking fine, no error messages.

But when I point my browser (from an external machine) to port 6273, I just get a "ERR_EMPTY_RESPONSE". 

I checked the /opt/omnisci/frontend directory, and it isnt there...I can't find the frontend directory anywhere actually.

I installed the open source through yum, following the official instructions, and everything else works fine, except the Web frontend.

Yes, I realise I need a serial for it to work, but it says in the docs that I need to enter it in the Immerse web portal...so... What do? Have I missed something?

**Comment by cdessanti** [comment]
Hi @baretomas,

since the release of OmniSci 4.5 that dropped the CE edition, in favor of OS edition, the immerse tool isn't included anymore.

so if you want to try-out Immerse interface on-premise you have to download and install the Enterprise Edition of the software, which includes Immerse and Back-end rendering (if you are trying out the GPU enabled version).

refer to this url to download and install the EE with yum 
https://docs.omnisci.com/latest/4_centos7-yum-gpu-ee-recipe.html

then you can ask your 30-days trial license here
https://www.omnisci.com/platform/downloads/enterprise

You can also try out Immerse and OmniscDB on our cloud following this link
https://omnisci.com/cloud

**Comment by baretomas** [comment]
Thanks for quick response!

**Comment by baretomas** [comment]
Bit quick on the close there:
Can I just yum the EE version on top of the open source one, and it will work, or do I have to do a clean install? 

Id like to try it out for 30 days, but I dont want to have to clean and reinstall 3 times to do it

**Comment by cdessanti** [comment]
Don't worry @baretomas ,

you can have the EE installed alongside the OS, if you do a tarball install; so you have to stop the OS edition if it's running, then download and install the EE using the tarball into another directory e.g.

/opt/omnisci-os
/opt/omnisci-ee

then you can run the install_omnisci_systemd.sh located in /opt/omnisci-ee/systemd folder to automatically create the services scripts using the actual path of the data catalog (You won't miss anything), then when the trial is over just run the same script on the OS edition. You data it will be still there.

**Comment by baretomas** [comment]
Thanks!!
