### ISSUE TITLE
about updates through joins.

### ISSUE THREAD

**Issue by ggcking** [omnisci/omniscidb#451]
I am glad to see then new release 5.0. Added support for updates through joins.
can you give me any demos ?

**Comment by cdessanti** [comment]
> I am glad to see then new release 5.0. Added support for updates through joins.
> can you give me any demos ?

Using correlated subqieries

update t1 set f1 = (select t2.f1 from t1, t2 where t1.id=t2.id)

Using exists operator
update t1 set f1=whatever you want
where exists (select 1 from t2 where t1.id=t2.id)

Its not exactly what you asked, but quite close

**Comment by ggcking** [comment]
@cdessanti 
I try your demo, but it is error.  
 create table t1 (f1 int, f2 varchar(10));
insert into t1 VALUES(1, 'a');
insert into t1 VALUES(2, 'b');
insert into t1 VALUES(3, 'c');
 create table t2 (f1 int, f2 varchar(10));
insert into t2 VALUES(1, '');
insert into t2 VALUES(2, '');
insert into t2 VALUES(3, '');

update t2 set f2 = (select t1.f2 from t1, t2 where t1.f1=t2.f1)
it is error:
Query failed : Exception: Exception occurred: null

what's the problem ?

**Comment by ggcking** [comment]
I run on docker.  
update t2 set f2 = (select t1.f2 from t1, t2 where t1.f1=t2.f1);
The omnisci db crash !!  joinHashTable.cpp:526 Check failed: inner_ti.is_string() == outer_ti.is_string() (1 == 0) ,

and I run 
update t2 set f2 = 'a' where exists (select 1 from t1,t2 where t1.f1=t2.f2),
it show "Exception: Function EXISTS() not supported."

**Comment by cdessanti** [comment]
> 
> 
> I run on docker.
> update t2 set f2 = (select t1.f2 from t1, t2 where t1.f1=t2.f1);
> The omnisci db crash !! joinHashTable.cpp:526 Check failed: inner_ti.is_string() == outer_ti.is_string() (1 == 0) ,
> 
> and I run
> update t2 set f2 = 'a' where exists (select 1 from t1,t2 where t1.f1=t2.f2),
> it show "Exception: Function EXISTS() not supported."

I'm sorry but I gave you the wrong directions, probably because I was on the phone.
So to use correrlated SQ

omnisql> update t2 set f2 = (select sample(t1.f2) from t1 where t2.f1=t1.f1);
omnisql> select * from t2;
f1|f2
1|a
2|b
3|c
3 rows returned.

I used sample function to be sure to have just one row returned from the CS.

About exists it doesn't work for me, while the not exist is working (weird), so

insert into t2 values(4,'d');

update t2 set f2='z' where not exists (select 1 from t1 where t2.f1=t1.f1);
omnisql> select * from t2;
f1|f2
1|a
2|b
3|c
4|z

The exists is supported on select, maybe isn't supported on updates yet.

**Comment by randyzwitch** [comment]
Here is our newest documentation for this feature:

https://docs.omnisci.com/latest/5_dml.html#update-via-subquery

Like always, we're continuously updating the functionality within OmniSciDB, so if what you are after isn't currently available, the next few releases will likely refine the update capabilities.
