### ISSUE TITLE
How to change the bind IP address?

### ISSUE THREAD

**Issue by averri** [omnisci/omniscidb#496]
How to specify the bind IP address for running the services?

I have followed the documents here https://github.com/omnisci/omniscidb/tree/master/docker for running Omniscidb on Docker containers. 

When running on Windows 10, the interface of Immerse is not available at http://localhost:6273.

Container logs:
```bash
$ docker logs omnisci                                                                                                                                                                                 
startomnisci 6 running                                                                                                                                                                                             
WARN: config file does not exist, ignoring: --config /omnisci-storage/omnisci.conf                                                                                                                                 
Backend TCP:  localhost:6274                                                                                                                                                                                       
Backend HTTP: localhost:6278                                                                                                                                                                                       
Frontend Web: localhost:6273                                                                                                                                                                                       
Calcite TCP:  localhost:6279                                                                                                                                                                                       
omnisci_server 246 started                                                                                                                                                                                       
2020-01-16T13:14:57.283658 E 246 MapDHandler.cpp:231 This build isn't CUDA enabled, will run on CPU
```

**Comment by andrewseidl** [comment]
Which build are you attempting to use? The open source edition of OmniSciDB unfortunately no longer includes Immerse, so that server will no longer start up (looks like we still need to modify the scripts to not output `the `Frontend Web` part). The [Enterprise Trial](https://www.omnisci.com/platform/downloads) does include Immerse though.

You can still use most of the Python/Jupyter, Node.js, JDBC, Julia, etc connectors with the open source edition. That being said, it looks like the docs in the repo are also a bit outdated since they don't open port 6274 (need to add `-p 6274:6274` to the `docker run` command). Slightly more up-to-date instructions are available at: https://docs.omnisci.com/latest/4_docker_cpu_os_recipe.html

And to answer your original question (for anyone coming across this later): the services currently bind to all available interfaces and currently do not support binding to just a single interface.

**Comment by averri** [comment]
Hi @andrewseidl, I'm using the open source version, the latest available here: https://releases.omnisci.com/os/tar/omnisci-os-latest-Linux-x86_64-cpu.tar.gz

Thank you for the information, I'll try the enterprise version.
