### ISSUE TITLE
COPY FROM .tsv FAILED

### ISSUE THREAD

**Issue by RobAShear** [omnisci/omniscidb#515]
I'm trying to load in the .tsv with this information:

```
COPY <table> FROM '/home/<user>/Documents/testfile.tsv' WITH (delimiter = '\t', quoted = 'false');

Loader truncated due to reject count.  Processed : 0 recs, Rejected: 103096 recs in 4.713000 secs
```

Previously I have used this same command to import files before. This is the first time it has not worked successfully. The importer rejected every single value. 

Any clue on how to fix this? Thanks!

**Comment by randyzwitch** [comment]
Hi @RobAShear - 

In my experience, when you see an unexpected result where every record is rejected, the table schema doesn't exactly match what you are expecting. Usually because there is one extra field, or one fewer than you expect.

If you go to the logs, it will print out the record and the error associated with it:

https://docs.omnisci.com/latest/7_logs_and_monitoring.html

**Comment by RobAShear** [comment]
> Hi @RobAShear -
> 
> In my experience, when you see an unexpected result where every record is rejected, the table schema doesn't exactly match what you are expecting. Usually because there is one extra field, or one fewer than you expect.
> 
> If you go to the logs, it will print out the record and the error associated with it:
> 
> https://docs.omnisci.com/latest/7_logs_and_monitoring.html

You the man! My db coworker added fields in the db without letting me know. Thank you for a quick and accurate reply!
