### ISSUE TITLE
query failed with exception: Query would use too much memory

### ISSUE THREAD

**Issue by LeeREVO** [omnisci/omniscidb#651]
When I execute a query: select a.id from a where exists (select id from b where a.id=b.id);
An Exception: Query would use too much memory came, the \memory_summary shows:

```
omnisql> \memory_summary
OmniSci Server CPU Memory Summary:
            MAX            USE      ALLOCATED           FREE
    51543.18 MB      686.65 MB     4096.00 MB     3409.35 MB

OmniSci Server GPU Memory Summary:
[GPU]            MAX            USE      ALLOCATED           FREE
  [0]    32126.50 MB      686.65 MB     4096.00 MB     3409.35 MB

```

How could I increase the ALLOCATED memory?

By the way I set:
cpu-buffer-mem-bytes = 0
gpu-buffer-mem-bytes = 0
in the omnisci.conf file

**Comment by cdessanti** [comment]
Hi LeeREVo,

When you get such message it's the watchdog that it's estimating that the query would need a massive amount of memory to run the query, so it's stopping the query's run before the execution.

The exception could be cause by an extremely high cardinality of the values you are using in the query, and I can suggest 2 ways to overcome the problem  and run the query

1 - You can try to disable the watchdog setting the enable-watchdog parameter to false in the omnisci.conf file
2 - Cahnge your query this way SELECT id FROM a where id in (SELECT DISTINCT id from b)

If the IDs are skewed you can think to load them as TEXT ENCODED DICTIONARY shared values to have uniform vales that would lead to perfect hashes.

Hopes this helps.
Candido

**Comment by LeeREVO** [comment]
Hi cdessanti,

Thank you for the solution~~! I set enable-watchdog = false and both query could get the correct result, but when I 
turn on watchdog and `SELECT id FROM a where id in (SELECT DISTINCT id from b)` , I got 

Exception: Projection query output result set on table(s): pool_300M_ids  would contain 180000000 rows, which is more than the current system limit of 32000000
So does watchdog also supervise the amount of opened rows?

**Comment by cdessanti** [comment]
Hi,

yep, choose the query that perfrom better or the one you prefer; the watchdog is rule based and is instructed to block query that would run for a long time and could potentially stall the system, so it also try to block the ones that ould return a massive amount of rows, because it could be an expensive and time consuming operation; the 32M number is weird, I remember that the number has been raised on new versions.

our database is primarily optimized for analytical query that return a relative small number of rows, so the limit, but we are constantly improving the software on various aspects; as an example on the latest release, the 5.6 we improved the runtime of geo join of 40 times on best case with optimization and over 100 times on default configuration.

candido

**Comment by LeeREVO** [comment]
Hi Candido,

Thank you for the detailed explanation! Will upgrade to the new version for a better performance~~
