### ISSUE TITLE
CREATE FOREIGN TABLE failed

### ISSUE THREAD

**Issue by zhouyuan** [omnisci/omniscidb#684]
Hi Omnisci developers, I'm trying on the foreign tables features on master branch and ran into below issue:
```
omnisql> CREATE FOREIGN TABLE testtable (t TEXT, i INTEGER[]) SERVER omnisci_local_csv WITH (file_path ='/home/nn/git/omniscidb/Tests/FsiDataFiles/example_1.csv');
Syntax error at: FOREIGN
```
Tried to look this in the docs but with no luck. Is there any configurations required to enable this feature?  

thanks, -yuan

**Comment by cdessanti** [comment]
Probably you have compiled without specifying the needing of fsi on cmle or you haven't enable it at server startup.
There is a parameter that enables the fsi

Scarica Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
From: Yuan ***@***.***>
Sent: Wednesday, September 29, 2021 4:46:26 PM
To: omnisci/omniscidb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [omnisci/omniscidb] CREATE FOREIGN TABLE failed (#684)


Hi Omnisci developers, I'm trying on the foreign tables features on master branch and ran into below issue:

omnisql> CREATE FOREIGN TABLE testtable (t TEXT, i INTEGER[]) SERVER omnisci_local_csv WITH (file_path ='/home/nn/git/omniscidb/Tests/FsiDataFiles/example_1.csv');
Syntax error at: FOREIGN


Tried to look this in the docs but with no luck. Is there any configurations required to enable this feature?

thanks, -yuan

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fomnisci%2Fomniscidb%2Fissues%2F684&data=04%7C01%7C%7C1d64945415a8405d84f108d98357eae0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637685235887975501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sVAp6F1w3271jvx3%2BO35cBlPOlWOCq3Lr%2B352InODjw%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHLFBFYLIEV3LX2XY567MNDUEMREFANCNFSM5FACF25A&data=04%7C01%7C%7C1d64945415a8405d84f108d98357eae0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637685235887975501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AbIpkCxLGJ6IB8ymWmPmshfViCxENxzJR%2BjAlLKlm3o%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C1d64945415a8405d84f108d98357eae0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637685235887985504%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BAs1LqiNcknkr9s9o5O%2BcCkcUxrQQUXXOawBbxa%2Bh6I%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C1d64945415a8405d84f108d98357eae0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637685235887985504%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0dT2aICA3v88MfxoksI1QQkMsTIr4x0M3dJv%2BiZR3Qs%3D&reserved=0>.

**Comment by zhouyuan** [comment]
Hi @cdessanti
 
Thanks for the hints, I just checked the CMakeLists.txt and didn't found any FSI related parameters, 
Here's the config during my build. Could you please point the detailed param? 
`cmake -DCMAKE_BUILD_TYPE=release -DENABLE_CUDA=off -DENABLE_FOLLY=off -DENABLE_AWS_S3=off -DENABLE_DBE=ON ..`

**Comment by zhouyuan** [comment]
@cdessanti I rechecked and found it's a cmd line option. Thanks!
`https://github.com/omnisci/omniscidb/blob/master/ThriftHandler/CommandLineOptions.cpp#L357-L360`

**Comment by cdessanti** [comment]
I also check the command line option from the source, but it is easier to check the form the documentation

https://docs-new.omnisci.com/installation-and-configuration/config-parameters#configuration-parameters-for-omniscidb

There are brief descriptions for each parameter and also examples on how to use them.

You can also get a list of parameters using the --help and --dev-options (the latter is for advanced parameters).

Regards,
Candido

Scarica Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zhouyuan** [comment]
@cdessanti I did check the configuration page but enable-fsi is not listed there, maybe the doc is a bit out dated. 
`--dev-options ` Thanks for sharing, this seems very helpful.

**Comment by cdessanti** [comment]
> @cdessanti I did check the configuration page but enable-fsi is not listed there, maybe the doc is a bit out dated. `--dev-options ` Thanks for sharing, this seems very helpful.

Yeah, the parameter description should be there because it is a publicly available switch. 
Thanks for pointing me out to this. I will ask internally (maybe there is a reason because it is omitted)
